In [1]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np #編寫numpy成np

In [3]:
np1 = np.array([1,2,3,4])#array,建立一個排序表


In [4]:
np2 =np.array((5,6,7,8))


In [5]:
print(np1)
print(np2)
print(type(np1),type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [6]:
np3 =np.arange(0,31,2)
print(np3)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [7]:
np4 =np.linspace(1,10,10)
print(np4)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
np5 = np.zeros((5,))
print(np5)

[0. 0. 0. 0. 0.]


In [9]:
np6 = np.ones((5,))
print(np6)

[1. 1. 1. 1. 1.]


In [10]:
np7=np.ones((5,2))
print(np7)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
listdate =[[1,2,3,4,5],[6,7,8,9,10]]


In [12]:
np8=np.array(listdate)


In [13]:
np8


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
print(np8)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
print('維度',np8.ndim)
print('形狀',np8.shape)
print('數量',np8.size)


維度 2
形狀 (2, 5)
數量 10


In [16]:
np9 = np.arange(1,21)
np9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
np10=np9.reshape(4,5)
print(np10)
np10

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
np10a = np9.reshape(5,4)
np10a
print(np10a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [20]:
np11=np.arange(1,21).reshape(5,4)
np11


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [23]:
np11[0,2]


3

In [22]:
np11[0,3]


4

In [24]:
np11[1,2]
print(np11[1:3,2])
print(np11[1:3,1:3])
print(np11[::2,::2])
print(np11[:,2])
print(np11[1,:])
print(np11[:,:])

[ 7 11]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]
 [17 19]]
[ 3  7 11 15 19]
[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [25]:
print('產生2x3,1~0的隨機浮點數/n')
np.random.rand(2,3)
print('產生2x3,常態分布浮點數/n')
np.random.randn(2,3)
print('產生0~4,但(不含5)整數/n')
np.random.randint(5)
print('產生2~4,(不含5)的5個整數/n')
np.random.randint(2,5,[5])
print('產生3個,0~1之間的隨機浮點數/n')
np.random.random(3),'/n',
np.random.random_sample(3),'/n',
np.random.sample(3)

產生2x3,1~0的隨機浮點數/n
產生2x3,常態分布浮點數/n
產生0~4,但(不含5)整數/n
產生2~4,(不含5)的5個整數/n
產生3個,0~1之間的隨機浮點數/n


array([0.29817687, 0.06091184, 0.01249935])

In [3]:
np12 =np.genfromtxt('scores.csv',delimiter=',',skip_header=1)
print(np12)


NameError: name 'np' is not defined